apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-serviceaccount
  labels:
    app: service-a
---
apiVersion: v1
kind: Pod
metadata:
  name: service-a
  labels:
    app: service-a
spec:
  serviceAccountName: my-serviceaccount
  containers:
  - name: service-a
    image: service-a:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 8080
    env:
    - name: KC_TOKEN_URL
      value: "http://keycloak.keycloak.svc.cluster.local/realms/kubernetes/protocol/openid-connect/token"
    - name: SERVICE_B_URL
      value: "http://service-b.service-b.svc.cluster.local/hello"
    readinessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 2
      periodSeconds: 5
    volumeMounts:
    - mountPath: /var/run/secrets/tokens
      name: vault-token
  volumes:
  - name: vault-token
    projected:
      sources:
      - serviceAccountToken:
          path: kctoken
          expirationSeconds: 600
          audience: http://keycloak.example.com/realms/kubernetes
